# Copyright 2014-2015 Dylan Benincasa. All rights reserved.
#
# En cour de création !
# Tous se que vous modifirait dans ce fichier ne changera rien sauf pour la ligne "Version" !
#

Config:
    Version: 8.0