name: Randomly-Craft
author: Prototyx5
version: 6.0
main: randomlycraft.fr.prototyx5.RandomlyCraft_Main
commands:
  ender:
    description: Fait spawn un Enderman.
  signal:
    description: Fait spawn un Ender_Signal.
  randomly-craft:
    description: Test du fonctionnement du plugin.
  wither:
    description: A venir.
permissions:
  stacker.stack:
    description:
  stacker.eject:
    description: