name: Randomly-Craft
author: Prototyx5
version: 7.0
main: randomlycraft.fr.prototyx5.RandomlyCraft_Main
commands:
  ender:
    description: Fait spawn un Enderman.
  signal:
    description: Fait spawn un Ender_Signal.
  randomly-craft:
    description: Test du fonctionnement du plugin.
  wither:
    description: A venir.
  fakejoin:
    aliases: [fj]
    description: Le joueur de votre choix rejoin le serveur pour de faux.
  talkas:
    aliases: [ta]
    description: Le joueur de votre choix dit se que vous voulez.
  fakeleave:  
    description: Le joueur de votre choix quite le serveur pour de faux.
permissions:
  stacker.stack:
    description:
  stacker.eject:
    description: